#!/usr/bin/env bash
#Script that loops 10 times (while) and print 
#    "'Best School' or,
#    "'good luck' on the 4th iteration
#    "'bad luck' based on the 8th iteration

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]
  then
    echo "bad luck"
  elif [ $i -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
